In [23]:
import numpy as np
import pandas as pd

train = pd.read_csv('/content/drive/MyDrive/빅데이터 과정 폴더/data/titanic/train.csv')

In [26]:
df = train.loc[:, ['PassengerId', 'Survived', 'Pclass', 'Sex', 'Age','SibSp','Fare','Embarked']]
sex_mean = train.groupby('Sex')['Age'].mean()
display(sex_mean)

Sex
female    27.915709
male      30.726645
Name: Age, dtype: float64